Feat: fakeapi
dscnitrourkela/project-maple pull request #27
Opened 2021-06-26 17:07 UTC by nayakastha

This Pull Request introduces the fake API and the data models that are essential for the development of the UI and ease in wireframing.

2021-06-27 07:29 UTC, nayakastha commented
![Screenshot (181)](https://user-images.githubusercontent.com/58568514/123536346-70336b80-d747-11eb-9be1-d443f071ca0f.png)
The page transaction on signing out happens without error.

2021-06-27 13:02 UTC, abhibhaw requested changes
![WhatsApp Image 2021-06-27 at 6 05 53 PM](https://user-images.githubusercontent.com/39991296/123545518-0aaaa380-d776-11eb-8a6f-3022c887497d.jpeg)
There is some error with logout flow

2021-06-27 18:58 UTC, nayakastha commented
> ![image](https://camo.githubusercontent.com/bbfafeb115e6ac546946541b09db5fb84b0b5beaebf0d28441e681a7d121dbd4/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f3130316b43364f4a6e63556869302f67697068792e6769663f6369643d64623931353864633779653872373076366f633177783961766d6f6d796d6d6f6b3775717a7370676764307870636e6c267269643d67697068792e6769662663743d67) ![image](https://camo.githubusercontent.com/fe9e912238e8855e6ccab104a952a01f605474eb51591fab27ea6619495ca127/68747470733a2f2f692e6962622e636f2f30396b5951736a2f506f776572656462792d31303070782d57686974652d566572742d4c6f676f2e706e67)
> Hello @nayakastha , That's a great improvement to the code. Have a pinch of paitence while the reviewer gets impressed by the changes you made. Here are some doggos for company while you are waiting for the merge and marching ahead with your Hacktoberfest Contributions, Check your [Dashboard](https://hacktoberfest.digitalocean.com/profile) for more information on Hacktoberfest. Stay safe 🚀 .

Woohoo!! @woofy is fixed

2021-06-28 19:54 UTC, abhibhaw requested changes
![2](https://user-images.githubusercontent.com/39991296/123695881-b9cfa380-d878-11eb-8d24-3c234b0e6dae.jpeg)

Stucking on Splash Screen

2021-06-28 19:54 UTC, abhibhaw commented on aptiche/lib/main.dart
> +              routes: <String, WidgetBuilder>{
@nayakastha consider moving routes to a separate file

2021-06-29 13:37 UTC, abhibhaw approved these changes
🎉🎉

2021-06-29 13:45 UTC, merged